# Generated by Django 4.2.3 on 2024-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("_", "Select"),
                            ("HT", "Half Time Played"),
                            ("FT", "Full Time Played"),
                            ("GS", "Goal Scored"),
                            ("AST", "Assist"),
                            ("CS", "Clean Sheet"),
                            ("3Sv", "3 Shots Saved"),
                            ("PKSv", "Penalty Saved"),
                            ("PKMs", "Penalty Missed"),
                            ("BSP", "Bonus Points"),
                            ("GC", "Goals Conceded"),
                            ("YC", "Yellow Card"),
                            ("RC", "Red Card"),
                            ("OG", "Own Goal"),
                        ],
                        default="_",
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
