# Generated by Django 4.2.3 on 2024-01-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="action",
            field=models.CharField(
                choices=[
                    ("_", "Select"),
                    ("G", "Goal"),
                    ("S", "Save"),
                    ("P", "Penalty"),
                    ("A", "Assist"),
                ],
                default="_",
                max_length=1,
            ),
        ),
    ]
