# Generated by Django 4.2.3 on 2024-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0002_alter_point_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="value",
        ),
        migrations.AlterField(
            model_name="point",
            name="action",
            field=models.CharField(
                choices=[
                    ("_", "Select"),
                    ("HT", "Half Time Played"),
                    ("FT", "Full Time Played"),
                    ("GS", "Goal Scored"),
                    ("AST", "Assist"),
                    ("CS", "Clean Sheet"),
                    ("3Sv", "3 Shots Saved"),
                    ("PKSv", "Penalty Saved"),
                    ("PKMs", "Penalty Missed"),
                    ("BSP", "Bonus Points"),
                    ("GC", "Goals Conceded"),
                    ("YC", "Yellow Card"),
                    ("RC", "Red Card"),
                    ("OG", "Own Goal"),
                ],
                default="_",
                max_length=4,
            ),
        ),
    ]
