# Generated by Django 4.2.3 on 2024-01-07 08:22

from django.db import migrations, models
import leagues.models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="code",
            field=models.CharField(
                default=leagues.models.generate_code, max_length=10, unique=True
            ),
        ),
    ]
