# Generated by Django 4.2.3 on 2024-02-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="title",
        ),
        migrations.AddField(
            model_name="league",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Title"),
        ),
    ]
