# Generated by Django 4.2.3 on 2024-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0002_alter_league_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="available",
        ),
        migrations.AddField(
            model_name="player",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerpoint",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
