# Generated by Django 4.2.3 on 2024-01-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0003_remove_player_available_player_flagged_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="caps",
                to="leagues.player",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="vice_captain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="vice_caps",
                to="leagues.player",
            ),
        ),
    ]
