# Generated by Django 4.2.3 on 2024-01-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0004_alter_team_captain_alter_team_vice_captain"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="-", max_length=100),
        ),
        migrations.AlterField(
            model_name="playerpoint",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acquired_points",
                to="leagues.player",
            ),
        ),
    ]
