# Generated by Django 4.2.3 on 2024-01-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0005_team_name_alter_playerpoint_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
