# Generated by Django 4.2.3 on 2024-01-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0006_alter_team_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="points",
            new_name="points_made",
        ),
        migrations.AlterField(
            model_name="playerpoint",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="leagues.player",
            ),
        ),
    ]
