# Generated by Django 4.2.3 on 2024-01-08 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0007_rename_points_player_points_made_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="points_made",
            new_name="points_model",
        ),
    ]
