# Generated by Django 4.2.3 on 2024-02-08 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0009_rename_points_model_player_points_made_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="max_selection_per_club",
        ),
    ]
