# Generated by Django 4.2.3 on 2024-02-08 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0011_league_max_selection_per_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to="leagues.league",
            ),
        ),
    ]
