# Generated by Django 4.2.3 on 2024-02-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0013_player_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="leagues.club",
                verbose_name="Clubs' Name",
            ),
        ),
    ]
