# Generated by Django 4.2.3 on 2024-02-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0014_alter_player_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="slug",
            field=models.SlugField(default="AK574D"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="leagues.club",
            ),
        ),
    ]
