# Generated by Django 4.2.3 on 2024-02-08 23:01

from django.db import migrations, models
import leagues.models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0015_league_slug_alter_player_club"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="slug",
        ),
        migrations.AlterField(
            model_name="league",
            name="code",
            field=models.CharField(
                db_index=True,
                default=leagues.models.generate_code,
                max_length=10,
                unique=True,
            ),
        ),
    ]
