# Generated by Django 4.2.3 on 2024-02-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0016_remove_league_slug_alter_league_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="slug",
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
