# Generated by Django 4.2.3 on 2024-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0017_league_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="slug",
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
